# Generated by Django 2.2.28 on 2022-09-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
    ]
