# Generated by Django 2.2.28 on 2022-09-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20220930_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='RecipesTags',
            new_name='RecipeTag',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeIngredient', to='recipes.Ingredients'),
        ),
        #migrations.AlterField(
        #    model_name='recipe',
        #    name='tags',
        #    field=models.ManyToManyField(related_name='recipes', through='recipes.RecipesTags', to='recipes.Tag'),
        #),

		#migrations.RenameModel(
        #    old_name='Ingredients',
        #    new_name='Ingredient',
        #),
        #migrations.DeleteModel(
        #    name='RecipeIngredients',
        #),
        #migrations.AddField(
        #    model_name='recipeingredient',
        #    name='ingredient',
        #    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipes.Ingredient'),
        #),
        #migrations.AddField(
        #    model_name='recipeingredient',
        #    name='recipe',
        #    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipes.Recipe'),
        #),
        #migrations.AddConstraint(
        #    model_name='recipeingredient',
        #    constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique ingredients'),
        #),
    ]
