# Generated by Django 2.2.28 on 2022-09-30 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_auto_20220930_1208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.RemoveField(
            model_name='recipeingredients',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipeingredients',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipes.Ingredient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipes.Recipe'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique ingredients'),
        ),
        migrations.DeleteModel(
            name='RecipeIngredients',
        ),
    ]
