# Generated by Django 2.2.28 on 2022-09-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220920_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='prep_time',
            new_name='cooking_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='picture',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
