# Generated by Django 2.2.28 on 2022-09-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20220921_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='quantity',
            new_name='amount',
        ),
    ]
