# Generated by Django 2.2.28 on 2022-09-26 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20220923_1215'),
        ('users', '0003_auto_20220920_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(through='recipes.Subscribe', to=settings.AUTH_USER_MODEL),
        ),
    ]
